### PR TITLE
expand CSV export file

### PR DESCRIPTION
**Pull request by betolink**
Originally we were only including the current variable in the exported files, now we are expanding them into the most relevant variables regardless of the current used in the plot. All the exported files will now have:

`mid_date , v, v_error, vx, vy, time_delta, satellite, mission, lon, lat`

### CODE REVIEW

**Comment by alex-s-gardner** [comment]
@betolink can we reorder the output and add vx_error, vy_error and epsg so that the output looks like this?

lat, lon, mid_date, v, v_error, vx, vx_error, vy, vy_error, date_dt, mission, satellite, epsg

the epsg is needed to know the orientation of vx and vy

**Comment by betolink** [comment]
@alex-s-gardner we can redorder, are we still using the lat-lon values or do you want the projected coordinates?

**Comment by alex-s-gardner** [comment]
> @alex-s-gardner we can redorder, are we still using the lat-lon values or do you want the projected coordinates?

I think lat and lon are still the most useful

**Comment by alex-s-gardner** [comment]
@betolink should we add units?:

mid_date, lat,  lon, v [m/yr], v_error [m/yr], vx [m/yr], vx_error [m/yr], vy [m/yr], vy_error [m/yr], date_dt [days], mission, satellite, epsg

**Comment by alex-s-gardner** [comment]
looks great!

**Pull request merged**
